# PURPOSE: gitlab-ci job definition file


# LOCAL VARIABLES
# ==================
variables:
  # defining dockerhub image name
  DOCKER_HUB_IMAGE: "ops4you/${CI_PROJECT_NAME}"


# COMMON PREPARATION TASKS
# ========================
before_script:
  # show environment info
  - echo "=> Running as USER $(whoami) on SERVER $(hostname -f)"
  - echo "=> Working dir is $(pwd)"


# LOCAL JOB ENTRIES
# ==================

# build docker image
docker_image:
  stage: BUILD
  image: docker:latest
  services:
    - docker:dind
  script:
    - sh build.sh
  tags:
    - docker


# eof
