---
# playbook for setting up ansible virtualenv
- name : "build.setenv"
  hosts: "{{ hosts | default('localhost') }}"
  gather_facts: no


  tasks:

    - name: "build.add.sourcedTopDir.to.activate.file"
      lineinfile:
        dest: "{{ activate_file_path }}"
        insertbefore: BOF
        line: 'sourcedFile=$BASH_SOURCE && sourcedFileDir=${sourcedFile%/*} && pushd $sourcedFileDir >/dev/null && sourcedFilePath=$PWD && popd >/dev/null && sourcedTopDir=${sourcedFilePath%/*};'

    - name: "build.set.sourcedTopDir.as.virtual_env"
      lineinfile:
        dest: "{{ activate_file_path }}"
        regexp: '^VIRTUAL_ENV='
        line:   'VIRTUAL_ENV="$sourcedTopDir"'

    - name: "build.add.load.site.env.title"
      lineinfile:
        dest: "{{ activate_file_path }}"
        line: '# LOAD SITE specific environment'

    - name: "build.add.load.site.env.if.exists"
      lineinfile:
        dest: "{{ activate_file_path }}"
        line: '[[ -f "$sourcedTopDir/cfg/ansible.env" ]] && source $sourcedTopDir/cfg/ansible.env'

    - name: "build.add.ansible.run.script"
      template:
        src: "{{ playbook_dir }}/files/run.sh"
        dest: "{{ BUILD_VENV }}/bin/run.sh"
        mode: 0755


# eof
